// winterarc — single config for all free resources, templates, quotes
// Edit here only — no backend needed. Project name is winterarc (WinterArc).

export const site = {
  name: 'WinterArc',
  domain: 'https://trywinterarc.vercel.app',
  tagline: 'Lock in while they coast.',
  hero: 'Disappear for 90 days. Come back unrecognizable.',
  dates: { start: '2026-10-01', end: '2026-12-31', label: 'Oct 1 → Dec 31', days: 92 },
  author: { name: 'Ashutosh Jha', url: 'https://ashutosh887.in', github: 'https://github.com/ashutosh887/winterarc', handle: 'ashutosh887' },
  builtOn: 'Vercel',
  support: { cta: 'Star on GitHub — it helps the community', github: 'https://github.com/ashutosh887/winterarc' },
}

export const resources: Record<string, { title: string; items: { name: string; url: string; desc: string; free: boolean }[] }> = {
  workout: {
    title: 'Workout — free',
    items: [
      { name: 'workout.lol', url: 'https://workout.lol/', desc: 'Generate free workout plans', free: true },
      { name: 'DAREBEE', url: 'https://darebee.com/', desc: '1000+ free no-equipment workouts', free: true },
      { name: 'Hevy (free tier)', url: 'https://www.hevy.com/', desc: 'Track lifts, free plan', free: true },
      { name: 'NerdFitness bodyweight', url: 'https://www.nerdfitness.com/blog/a-beginners-guide-to-bodyweight-workouts/', desc: 'Beginner bodyweight guide', free: true },
    ],
  },
  nutrition: {
    title: 'Nutrition — free',
    items: [
      { name: 'MyFitnessPal (free)', url: 'https://www.myfitnesspal.com/', desc: 'Track protein & calories', free: true },
      { name: 'Cronometer (free)', url: 'https://cronometer.com/', desc: 'Micronutrient tracker', free: true },
      { name: 'EatThisMuch (free)', url: 'https://www.eatthismuch.com/', desc: 'Free meal planner', free: true },
    ],
  },
  focus: {
    title: 'Focus & Work — free',
    items: [
      { name: 'Pomofocus', url: 'https://pomofocus.io/', desc: 'Free pomodoro timer', free: true },
      { name: 'Flow — free', url: 'https://flow.app/', desc: 'Minimal focus timer', free: true },
      { name: 'Notion (free)', url: 'https://www.notion.so/', desc: 'Free workspace for arcs', free: true },
    ],
  },
  mind: {
    title: 'Mind — free',
    items: [
      { name: 'Insight Timer (free)', url: 'https://insighttimer.com/', desc: 'Free meditation library', free: true },
      { name: 'Waking Up intro (free)', url: 'https://www.wakingup.com/', desc: 'Intro meditations free', free: true },
      { name: '5-min journal (free PDF)', url: 'https://www.intelligentchange.com/blogs/news/free-printable-journal', desc: 'Free gratitude templates', free: true },
    ],
  },
  sleep: {
    title: 'Sleep — free',
    items: [
      { name: 'Sleep Foundation guides', url: 'https://www.sleepfoundation.org/how-sleep-works', desc: 'Free sleep hygiene guides', free: true },
      { name: 'Huberman sleep toolkit', url: 'https://www.hubermanlab.com/newsletter', desc: 'Free newsletter toolkit', free: true },
    ],
  },
}

export const templates: { id: string; name: string; icon: string; habitIds: string[]; desc: string }[] = [
  { id: 'body', name: 'Body Arc', icon: '💪', habitIds: ['gym', 'steps', 'sleep', 'nutrition', 'water'], desc: 'Train, move, sleep, eat clean. Simple and brutal.' },
  { id: 'mind', name: 'Mind Arc', icon: '🧘', habitIds: ['meditation', 'journaling', 'reading', 'sleep', 'phone-pm'], desc: 'Calm mornings, reading, journaling, phone curfew.' },
  { id: 'grind', name: 'Grind Arc', icon: '🎯', habitIds: ['work', 'sleep', 'gym', 'reading', 'phone-am'], desc: 'Deep work 90m, train, read, no phone AM.' },
  { id: 'no-sugar', name: 'No-Sugar Arc', icon: '🥗', habitIds: ['nutrition', 'protein', 'water', 'sleep', 'gym'], desc: 'No sugar/junk, protein target, water, sleep.' },
  { id: 'minimal', name: 'Minimal (3)', icon: '❄️', habitIds: ['gym', 'sleep', 'work'], desc: 'Just 3 — perfect for starting. Add more later.' },
]

// 120 quotes — covers 92-day arc + buffer for future arcs post-Jan. Shown rotating, history + future preview available.
export const quotes: { q: string; a: string }[] = [
  { q: 'Discipline is choosing between what you want now and what you want most.', a: 'Abraham Lincoln' },
  { q: 'You do not rise to the level of your goals. You fall to the level of your systems.', a: 'James Clear' },
  { q: 'The winter will ask what you did all summer.', a: '—' },
  { q: 'Lock in while they coast. Unleash while they scramble.', a: 'Winter Arc' },
  { q: 'Small hinges swing big doors.', a: '—' },
  { q: 'Consistency is harder than intensity. Harder. And more powerful.', a: '—' },
  { q: 'No zero days. A little is still a lot.', a: '—' },
  { q: 'You are what you do when no one is clapping.', a: '—' },
  { q: '90 days of boring effort beats 3 days of heroic effort.', a: '—' },
  { q: 'The work you do in the dark puts you in the light.', a: '—' },
  { q: 'Motivation gets you going, but discipline keeps you growing.', a: 'John C. Maxwell' },
  { q: 'In the middle of difficulty lies opportunity.', a: 'Albert Einstein' },
  { q: 'First it hurts, then it becomes habit.', a: '—' },
  { q: 'Stay the course. January you will thank October you.', a: '—' },
  { q: 'Build body. Build career. Fix sleep. Kill bad habits.', a: 'Winter Arc' },
  { q: 'Boring consistency creates interesting results.', a: '—' },
  { q: 'Your future needs you. Your past doesn’t.', a: '—' },
  { q: 'Sweat in peace, shine in war.', a: '—' },
  { q: 'Don’t watch the clock; do what it does. Keep going.', a: 'Sam Levenson' },
  { q: 'The pain you feel today is the strength you feel tomorrow.', a: '—' },
  { q: 'Focus is a matter of deciding what not to do.', a: '—' },
  { q: 'If you want to go fast go alone, if you want to go far go together.', a: '—' },
  { q: 'What you do every day matters more than what you do once in a while.', a: 'Gretchen Rubin' },
  { q: 'The secret of getting ahead is getting started.', a: 'Mark Twain' },
  { q: 'You can’t cross the sea merely by standing and staring at the water.', a: 'Rabindranath Tagore' },
  { q: 'Success is the sum of small efforts, repeated day in and day out.', a: 'Robert Collier' },
  { q: 'Winners do what losers don’t want to do.', a: '—' },
  { q: 'Make each day your masterpiece.', a: 'John Wooden' },
  { q: 'Discipline is the bridge between goals and accomplishment.', a: 'Jim Rohn' },
  { q: 'The only way to do great work is to love what you do.', a: 'Steve Jobs' },
  { q: 'Fall seven times, stand up eight.', a: 'Japanese Proverb' },
  { q: 'It does not matter how slowly you go as long as you do not stop.', a: 'Confucius' },
  { q: 'Act as if what you do makes a difference. It does.', a: 'William James' },
  { q: 'You miss 100% of the shots you don’t take.', a: 'Wayne Gretzky' },
  { q: 'Hard choices, easy life. Easy choices, hard life.', a: 'Jerzy Gregorek' },
  { q: 'The cold doesn’t care. Show up anyway.', a: '—' },
  { q: 'One day or day one. You decide.', a: '—' },
  { q: 'Be stronger than your strongest excuse.', a: '—' },
  { q: 'Do the work. Especially when you don’t feel like it.', a: '—' },
  { q: 'Habits form by repetition, not by motivation.', a: '—' },
  { q: 'Sleep is a weapon. Use it.', a: '—' },
  { q: 'No sugar today is energy tomorrow.', a: '—' },
  { q: 'Water first. Phone later.', a: '—' },
  { q: 'Walk while they scroll.', a: '—' },
  { q: 'Read 10 pages. Your future mind will thank you.', a: '—' },
  { q: 'Write three lines. That’s a journal.', a: '—' },
  { q: 'Breathe for 10 minutes. The day gets quieter.', a: '—' },
  { q: 'Sunlight before screenlight.', a: '—' },
  { q: 'Tidy desk, tidy mind.', a: '—' },
  { q: 'Spend nothing today, keep freedom tomorrow.', a: '—' },
  { q: 'Cold water, warm will.', a: '—' },
  { q: 'Early bed, early win.', a: '—' },
  { q: 'Do 30 minutes. Walk counts.', a: '—' },
  { q: 'Protein at every meal. Simple.', a: '—' },
  { q: 'Phone down by 21:00. Night is yours.', a: '—' },
  { q: 'The gym is a vote for the person you’re becoming.', a: '—' },
  { q: 'Steps don’t lie.', a: '—' },
  { q: 'Write before you consume.', a: '—' },
  { q: 'One habit held is better than ten planned.', a: '—' },
  { q: 'Keep the streak alive, not perfect.', a: '—' },
  { q: 'Miss once, never twice.', a: '—' },
  { q: 'Show up. The rest compounds.', a: '—' },
  { q: 'You are your schedule.', a: '—' },
  { q: 'Quiet work, loud results.', a: '—' },
  { q: 'Make the bed. Win the morning.', a: '—' },
  { q: 'Journal the miss, don’t hide it.', a: '—' },
  { q: 'The arc doesn’t care about your mood.', a: '—' },
  { q: 'Trade sugar for strength.', a: '—' },
  { q: 'Drink water like it’s your job.', a: '—' },
  { q: 'Outside 20 minutes, every day.', a: '—' },
  { q: 'No alcohol is a superpower in winter.', a: '—' },
  { q: 'Deep work before shallow work.', a: '—' },
  { q: 'Ship one thing daily.', a: '—' },
  { q: 'The phone stays out of the room until the first block is done.', a: '—' },
  { q: 'Bed made, kitchen clean, mind clear.', a: '—' },
  { q: 'Consistency is a love language to your future self.', a: '—' },
  { q: 'Be the person who doesn’t break promises to themselves.', a: '—' },
  { q: 'Today’s small win is tomorrow’s momentum.', a: '—' },
  { q: 'You don’t need more time, you need fewer distractions.', a: '—' },
  { q: 'The fastest way to change is to act.', a: '—' },
  { q: 'Hate the excuse, not the winter.', a: '—' },
  { q: 'Cold air, clear head.', a: '—' },
  { q: 'Do it tired. Do it cold. Do it anyway.', a: '—' },
  { q: 'Your arc, your rules, your record.', a: '—' },
  { q: 'Keep the grid honest.', a: '—' },
  { q: 'Green squares are votes for January you.', a: '—' },
  { q: 'One more rep when you want to quit — that’s the arc.', a: '—' },
  { q: 'The hardest habit is the one you skip first.', a: '—' },
  { q: 'Protect the morning, the day follows.', a: '—' },
  { q: 'No zero days in winter.', a: '—' },
  { q: 'Finish the set. Finish the day.', a: '—' },
  { q: 'You can’t cheat the calendar.', a: '—' },
  { q: '92 days is short if you start today.', a: '—' },
  { q: 'The arc is not 90 days, it’s today repeated.', a: '—' },
  { q: 'Make January jealous of October you.', a: '—' },
  { q: 'Do it before you feel ready.', a: '—' },
  { q: 'The cost of waiting is who you could have been.', a: '—' },
  { q: 'What you track, you tend to improve.', a: '—' },
  { q: 'Streaks are just proof you kept a promise.', a: '—' },
  { q: 'Better 20 minutes than 0 minutes.', a: '—' },
  { q: 'Sleep early, win early.', a: '—' },
  { q: 'Eat like you respect your training.', a: '—' },
  { q: 'Move every day. Minimum is a walk.', a: '—' },
  { q: 'The dark months make the light months.', a: '—' },
  { q: 'Stay locked. The noise can wait.', a: '—' },
  { q: 'Your phone will still be there after the block.', a: '—' },
  { q: 'A short walk beats a long excuse.', a: '—' },
  { q: 'You don’t have to be perfect, just present.', a: '—' },
  { q: 'Write the minimum, keep the chain.', a: '—' },
  { q: 'Small wins, big identity.', a: '—' },
  { q: 'The calendar is the accountability.', a: '—' },
  { q: 'January is graduation, not starting line.', a: '—' },
  { q: 'Do the boring work beautifully.', a: '—' },
  { q: 'Be the person winter couldn’t stop.', a: '—' },
  { q: 'One more day, one more square.', a: '—' },
  { q: 'The world hibernates. You don’t.', a: '—' },
  { q: 'Keep the promise you made in September.', a: '—' },
  { q: 'Your habits are your future in disguise.', a: '—' },
  { q: 'Cold showers don’t make you tough. Showing up does.', a: '—' },
  { q: 'Sleep is not a reward for work; work is a reward for sleep.', a: '—' },
  { q: 'Read, even when you don’t want to.', a: '—' },
  { q: 'The most powerful habit is the one you keep when it’s inconvenient.', a: '—' },
]
