export const site = {
  name: 'WinterArc',
  domain: 'https://trywinterarc.vercel.app',
  tagline: 'Lock in while they coast.',
  hero: 'Disappear for 90 days. Come back unrecognizable.',
  author: { name: 'Ashutosh Jha', url: 'https://ashutosh887.in', github: 'https://github.com/ashutosh887/winterarc', handle: 'ashutosh887_' },
  builtOn: 'Vercel',
  support: { cta: 'Star on GitHub. It helps', github: 'https://github.com/ashutosh887/winterarc' },
}

export const resources: Record<string, { title: string; items: { name: string; url: string; desc: string }[] }> = {
  workout: {
    title: 'Workout',
    items: [
      { name: 'workout.lol', url: 'https://workout.lol/', desc: 'Build a routine from the muscles you pick' },
      { name: 'DAREBEE', url: 'https://darebee.com/', desc: 'No equipment workouts, no ads' },
      { name: 'Hevy', url: 'https://hevy.com/', desc: 'Log lifts and track volume' },
      { name: 'NerdFitness', url: 'https://www.nerdfitness.com/blog/beginner-body-weight-workout-burn-fat-build-muscle/', desc: '20 minute beginner bodyweight routine' },
    ],
  },
  nutrition: {
    title: 'Nutrition',
    items: [
      { name: 'Cronometer', url: 'https://cronometer.com/', desc: 'Calories and micronutrients' },
      { name: 'MyFitnessPal', url: 'https://www.myfitnesspal.com/', desc: 'Protein and calorie logging' },
      { name: 'EatingWell meal plans', url: 'https://www.eatingwell.com/category/4288/meal-plans/', desc: 'Weekly meal plans, no account' },
    ],
  },
  focus: {
    title: 'Focus and work',
    items: [
      { name: 'Pomofocus', url: 'https://pomofocus.io/', desc: 'Pomodoro timer in the browser' },
      { name: 'Flow', url: 'https://flow.app/', desc: 'Minimal focus timer for Mac and iOS' },
      { name: 'Notion', url: 'https://www.notion.so/', desc: 'Somewhere to keep the plan' },
    ],
  },
  mind: {
    title: 'Mind',
    items: [
      { name: 'Insight Timer', url: 'https://insighttimer.com/', desc: 'Large library of guided meditations' },
      { name: 'UCLA Mindful', url: 'https://www.uclahealth.org/uclamindful/free-guided-meditations', desc: 'Guided meditations from UCLA Health' },
      { name: 'Greater Good gratitude', url: 'https://ggia.berkeley.edu/practice/gratitude_journal', desc: 'Berkeley gratitude journal practice' },
    ],
  },
  sleep: {
    title: 'Sleep',
    items: [
      { name: 'Sleep Foundation', url: 'https://www.sleepfoundation.org/how-sleep-works', desc: 'How sleep actually works' },
      { name: 'Huberman sleep toolkit', url: 'https://www.hubermanlab.com/newsletter/toolkit-for-sleep', desc: 'Protocol for falling and staying asleep' },
    ],
  },
}

export const templates: { id: string; name: string; icon: string; habitIds: string[]; desc: string }[] = [
  { id: 'body', name: 'Body arc', icon: 'dumbbell', habitIds: ['gym', 'steps', 'sleep', 'nutrition', 'water'], desc: 'Train. Move. Sleep. Eat clean.' },
  { id: 'mind', name: 'Mind arc', icon: 'wind', habitIds: ['meditation', 'journaling', 'reading', 'sleep', 'phone-pm'], desc: 'Calm mornings. Reading. Journaling. Phone curfew.' },
  { id: 'grind', name: 'Grind arc', icon: 'target', habitIds: ['work', 'sleep', 'gym', 'reading', 'phone-am'], desc: 'Deep work 90 min. Train. Read. No phone in the morning.' },
  { id: 'no-sugar', name: 'No sugar arc', icon: 'salad', habitIds: ['nutrition', 'protein', 'water', 'sleep', 'gym'], desc: 'No sugar or junk. Hit protein. Drink water. Sleep.' },
  { id: 'minimal', name: 'Minimal', icon: 'snowflake', habitIds: ['gym', 'sleep', 'work'], desc: 'Just three. Good place to start. Add more later.' },
]

export const challenges: { id: string; label: string; icon: string; desc: string; metric: 'checks' | 'perfect' | 'streak' | 'pct'; target: number }[] = [
  { id: 'first', label: 'First check', icon: 'check', desc: 'Log one habit', metric: 'checks', target: 1 },
  { id: 'perfect1', label: 'Perfect day', icon: 'star', desc: 'Every habit in one day', metric: 'perfect', target: 1 },
  { id: 'streak3', label: '3 day streak', icon: 'flame', desc: 'Three perfect days in a row', metric: 'streak', target: 3 },
  { id: 'streak7', label: '7 day streak', icon: 'mountainSnow', desc: 'Seven perfect days in a row', metric: 'streak', target: 7 },
  { id: 'perfect10', label: '10 perfect', icon: 'gem', desc: 'Ten perfect days total', metric: 'perfect', target: 10 },
  { id: 'streak14', label: '14 day lock', icon: 'snowflake', desc: 'Fourteen perfect days in a row', metric: 'streak', target: 14 },
  { id: 'half', label: 'Halfway', icon: 'hourglass', desc: 'Half of all checks done', metric: 'pct', target: 50 },
  { id: 'streak30', label: '30 day forge', icon: 'gem', desc: 'Thirty perfect days in a row', metric: 'streak', target: 30 },
  { id: 'perfect30', label: '30 perfect', icon: 'crown', desc: 'Thirty perfect days total', metric: 'perfect', target: 30 },
  { id: 'complete75', label: '75 percent', icon: 'rocket', desc: 'Three quarters of all checks', metric: 'pct', target: 75 },
  { id: 'graduate', label: 'Graduation', icon: 'graduationcap', desc: 'Every single day perfect', metric: 'perfect', target: 0 },
]

export const quotes: string[] = [
  "Nobody is watching. That is what makes it count.",
  "The grid does not care how you felt about it.",
  "A missed day stays missed. That is the honest part.",
  "Your habits are voting on who you become.",
  "Come back in January and let the grid do the talking.",
  "Start ugly. Fix it while it moves.",
  "You are not behind. You just have not started.",
  "Do it before you have time to negotiate.",
  "Ready is a result, not a feeling.",
  "The first rep is the only one that is hard to schedule.",
  "Doing it tired is the whole skill.",
  "The work does not know you are tired.",
  "You will not always want to. Go anyway.",
  "Tired is not the same as unable.",
  "Show up at the floor, not the ceiling.",
  "Small and boring, every day, beats big and rare.",
  "One missed day is noise. Two in a row is a decision.",
  "Every clean day makes the next one cheaper.",
  "Momentum is expensive to build and cheap to keep.",
  "Decide once. Then stop deciding.",
  "Make the bar so low you cannot justify missing it.",
  "Skipping once teaches you that skipping is allowed.",
  "Your standards are whatever you accept twice.",
  "Half effort still fills the square. Zero does not.",
  "Effort you can repeat beats effort you can brag about.",
  "An average day done beats a perfect day planned.",
  "Progress is quiet. Excuses are loud.",
  "Talking about it burns the same energy as doing it.",
  "Excuses are plans you made for failing.",
  "Do not confuse being busy with being consistent.",
  "Pick fewer things and refuse to miss them.",
  "Three you never miss beats eight you miss half of.",
  "You are not lazy. You are unclear. Pick three things.",
  "Stop optimising. Start repeating.",
  "You do not need a better plan. You need today.",
  "Comfort is the thing you are actually competing with.",
  "Hard now or hard later. Pick your hard.",
  "There is no version of this that feels good every day.",
  "Do it while it is inconvenient. That is the test.",
  "If it were easy you would not need a tracker.",
  "No shortcut survives ninety days.",
  "You are always training something. Pick what.",
  "The streak is not the prize. The person is.",
  "Discipline is remembering what you already decided.",
  "Being consistent is a skill, not a trait.",
  "Nobody drifts into discipline.",
  "The point is not to feel good. It is to be different.",
  "Motivation is a mood. Build something duller than a mood.",
  "The mood follows the action, not the other way round.",
  "You do not have to be motivated. You have to be moving.",
  "Waiting to feel like it is how the year disappears.",
  "Twenty minutes today beats two hours next week.",
  "Nothing you skip today gets easier tomorrow.",
  "Every skipped day borrows from one you have not lived.",
  "You do not need more time. You need less negotiation.",
  "The best day to start was earlier. The next best is now.",
  "Everyone is impressive in January. Be impressive in November.",
  "Winter is long. Use it or watch it pass.",
  "Winter rewards whoever refused to coast.",
  "You get one shot at this particular winter.",
  "Nobody claps for the ninth week. Do it anyway.",
  "Rest is part of it. Quitting is not.",
  "The version of you that quits always has a good reason.",
  "You are three days from momentum. Every time.",
  "Missing one day is recoverable. Deciding to stop is not.",
  "Do the thing you would skip if nobody asked.",
  "Do enough today that tomorrow is not a rescue mission.",
  "Discipline buys you options later.",
  "The people ahead of you just did not stop.",
  "Fill the square. Feelings are optional.",
]
